---
- hosts: localhost
  gather_facts: no
  vars:
    domain: "yourdomain.com"
    token: "yourapitoken"
  tasks:
  - name: create TXT record
    cloudflare_dns:
      api_token: "{{ token }}"
      domain: "{{ domain }}"
      record: "test"
      type: "TXT"
      value: "Hello World"